# Generated by Django 3.0 on 2019-12-05 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_members',
            name='group1',
        ),
        migrations.RemoveField(
            model_name='group_members',
            name='member1',
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='group_members',
        ),
    ]
