# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-02 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='udb',
        ),
    ]
