# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-11 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbvhello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schoolname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='cbvhello.school')),
            ],
        ),
    ]
