# Generated by Django 3.0 on 2019-12-05 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_auto_20191205_0125'),
        ('posts', '0003_auto_20180816_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='groupname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
